### ISSUE TITLE
I am getting vnc error

### ISSUE THREAD

**Issue by frank3427** [nickcharlton/packer-esxi#2]
docker@Docker1:~/esxi/packer-esxi$ packer build -var-file variables.json ubuntu-1604-base.json
ubuntu-1604-base output will be in this color.

==> ubuntu-1604-base: Downloading or copying ISO
    ubuntu-1604-base: Found already downloaded, initial checksum matched, no download needed: http://releases.ubuntu.com/xenial/ubuntu-16.04.5-server-amd64.iso
==> ubuntu-1604-base: Creating floppy disk...
    ubuntu-1604-base: Copying files flatly from floppy_files
    ubuntu-1604-base: Copying file: preseed/ubuntu.cfg
    ubuntu-1604-base: Done copying files from floppy_files
    ubuntu-1604-base: Collecting paths from floppy_dirs
    ubuntu-1604-base: Resulting paths from floppy_dirs : []
    ubuntu-1604-base: Done copying paths from floppy_dirs
==> ubuntu-1604-base: Uploading Floppy to remote machine...
==> ubuntu-1604-base: Uploading ISO to remote machine...
==> ubuntu-1604-base: Creating required virtual machine disks
==> ubuntu-1604-base: Building and writing VMX file
==> ubuntu-1604-base: Registering remote VM...
==> ubuntu-1604-base: Starting virtual machine...
==> ubuntu-1604-base: Waiting 10s for boot...
==> ubuntu-1604-base: Connecting to VM via VNC (172.25.2.151:5900)
==> ubuntu-1604-base: Error handshaking with VNC: no suitable auth schemes found. server supported: []byte{0x1}
==> ubuntu-1604-base: Stopping virtual machine...
==> ubuntu-1604-base: Destroying virtual machine...
Build 'ubuntu-1604-base' errored: Error handshaking with VNC: no suitable auth schemes found. server supported: []byte{0x1}

==> Some builds didn't complete successfully and had errors:
--> ubuntu-1604-base: Error handshaking with VNC: no suitable auth schemes found. server supported: []byte{0x1}

==> Builds finished but no artifacts were created.
docker@Docker1:~/esxi/packer-esxi$

**Comment by robarros** [comment]
same

**Comment by kusold** [comment]
You are probably on ESXI 6.7. I ran into the same error, but the issue appears to be upstream: https://github.com/hashicorp/packer/issues/6482

**Comment by kopfpilot** [comment]
Assumed you follwed everything in https://nickcharlton.net/posts/using-packer-esxi-6.html

What you miss is a setting in the builder to disable the vnc passwort:
> "vnc_disable_password": true,

**Comment by nickcharlton** [comment]
Thanks for reporting this! Yeah, 6.7 changes things and it no longer works. I'm working on a follow up which uses the `vsphere-iso` builder instead, which, if you're able to, I'd recommend using.
