### ISSUE TITLE
How the builder export the VM at the end using ovftool?, I mean where did you mentioned that to export?

### ISSUE THREAD

**Issue by muthurd** [nickcharlton/packer-esxi#3]
Packer version 1.3.2
Host - esxi 6
JSON -  ubuntu-1604-base.json 

I was successfully able to run this, but got a question, How the builder export the VM at the end using ovftool?, I mean where did you mentioned that to export?.

**Comment by nickcharlton** [comment]
Do you mean where in the Packer JSON? If so, you'll want something like this:

```json
 "post-processors": [
    {
      "type": "shell-local",
      "inline": ["ovftool debian-9-base/debian-9-base.vmx debian-9-base/debian-9-base.ova"]
    }
  ]
```
