### ISSUE TITLE
ovftool validation error: fork/exec : no such file or directory

### ISSUE THREAD

**Issue by lokeshmd** [nickcharlton/packer-esxi#4]
packer build -var-file variables.json ubuntu-1604-base.json                                                                        
ubuntu-1604-base output will be in this color.

1 error(s) occurred:

* ovftool validation error: fork/exec : no such file or directory;

**Comment by ghost** [comment]
i've the same issue

**Comment by Remarknl** [comment]
Just install [ovftool](https://code.vmware.com/web/tool/4.3.0/ovf) on your host

**Comment by nickcharlton** [comment]
Closing this as that's very likely solved by installing `ovftool`.
